
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = '\xea\n\xb2\x1e\x97W\xa73t\xc1\xcc\x05\x8f_A\r'
    
_lr_action_items = {'REAL':([1,5,],[12,12,]),'INTD':([1,5,],[4,4,]),'SCI':([1,5,],[9,9,]),'VID':([1,],[5,]),'MODULE':([0,],[1,]),'INTP':([1,5,],[10,10,]),'END':([3,4,6,7,8,9,10,11,12,13,14,],[-5,-7,-4,15,-3,-11,-9,-6,-10,-8,16,]),'INTX':([1,5,],[13,13,]),'$end':([2,15,16,],[0,-1,-2,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'real':([1,5,],[3,3,]),'sci':([1,5,],[11,11,]),'int':([1,5,],[6,6,]),'expr':([1,5,],[7,14,]),'module':([0,],[2,]),'literal':([1,5,],[8,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> module","S'",1,None,None,None),
  ('module -> MODULE expr END','module',3,'p_module','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',16),
  ('module -> MODULE VID expr END','module',4,'p_module','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',17),
  ('expr -> literal','expr',1,'p_expr','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',29),
  ('literal -> int','literal',1,'p_literal','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',35),
  ('literal -> real','literal',1,'p_literal','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',36),
  ('literal -> sci','literal',1,'p_literal','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',37),
  ('int -> INTD','int',1,'p_int','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',43),
  ('int -> INTX','int',1,'p_int','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',44),
  ('int -> INTP','int',1,'p_int','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',45),
  ('real -> REAL','real',1,'p_real','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',52),
  ('sci -> SCI','sci',1,'p_sci','/storage/dcollins/Dropbox/Code/mara-lang/bootstrap/mara/parser.py',58),
]
